### ISSUE TITLE
iOS层的还没有实现啊

### ISSUE THREAD

**Issue by LINGLemon** [crazycodeboy/flutter_splash_screen#2]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by LINGLemon** [comment]
这个我已经实现了，添加了一个UIWindow，window上面显示和启动图一样的图，盖在最上层，然后通过channel的方式在dart层通知iOS native把这个window移除就行。

**Comment by FrankenApps** [comment]
You know, that this is for flutter, right?
